AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Twitter Feed Analysis
Resources:
  TrumpFeed:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.sample.twitter.TwitterRequestHandler
      Runtime: java8
      CodeUri: s3://arungupta/twitter-feed-1.0-SNAPSHOT.jar
      Timeout: 30
      MemorySize: 1024
      Environment:
        Variables:
          DYNAMODB_REGION: us-west-1
      Role: arn:aws:iam::091144949931:role/microserviceRole
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
